Fix some issues in AppStream MetaInfo
mcallegari/qlcplus pull request #1238
Opened 2020-09-09 14:10 UTC by jeromelebleu

This tries to fix some issues reported by [AppStream Report for Debian](https://appstream.debian.org/sid/main/issues/qlcplus.html):
* **asv-url-not-secure**: use HTTPS in homepage URL of MetaInfo
* **missing-desktop-file**: define `<launchable>` tag in desktop-application MetaInfo to associate it with the .desktop file
* **metainfo-no-summary**: I guess that it would be fixed with the `<launchable>` tag since it is said that either .desktop file should have a `Comment=` field set or the component MetaInfo file should have a `summary` tag - which is the case.

2020-09-10 15:22 UTC, mcallegari requested changes

2020-09-10 15:22 UTC, mcallegari commented on platforms/linux/org.qlcplus.QLCPlus.appdata.xml
>   <url type="homepage">http://www.qlcplus.org/</url>
https

2020-09-10 15:22 UTC, mcallegari commented on platforms/linux/org.qlcplus.QLCPlusFixtureEditor.appdata.xml
>   <url type="homepage">http://www.qlcplus.org/</url>
https

2020-09-10 15:55 UTC, jeromelebleu commented
@mcallegari Thanks, I missed those files!

2020-09-14 06:56 UTC, mcallegari approved these changes

2020-09-14 06:56 UTC, merged