Updated Cameo and Chauvet fixtures to have Gobo and Gobo Rotation Preset
mcallegari/qlcplus pull request #1249
Opened 2020-12-09 13:57 UTC by kluszon

- Added rotation presets to color wheels and gobo wheels
- Added rotation presets to gobo rotation channels
- Added GoboMacro presets to gobo wheels
- Added ActsOn where relevant
- Added shutter and mainenance presets where previously missed

2020-12-12 10:16 UTC, mcallegari requested changes

2020-12-12 10:16 UTC, mcallegari commented on resources/fixtures/Cameo/Cameo-LED-Moving-Head-60W-CLMHRGB60W.qxf
> +  <Capability Min="192" Max="255" Preset="RotationClockwiseSlowToFast">Rainbow, direction of rotation forwards (speed slow - fast)</Capability>
According to the manual this is backward rotation. Please fix

2020-12-12 10:16 UTC, mcallegari commented on resources/fixtures/Chauvet/Chauvet-Q-Spot-260-LED.qxf
> +  <Capability Min="153" Max="255" Preset="RotationCounterClockwise">Rainbow or linear effect</Capability>
Shouldn't this be clockwise?

2020-12-12 10:16 UTC, mcallegari commented on resources/fixtures/Chauvet/Chauvet-Rogue-RH1-Hybrid.qxf
> +  <Capability Min="132" Max="167" Preset="RampDownSlowToFast">Fast close, slow open (slow to fast)</Capability>
This should be RampUp

2020-12-14 10:24 UTC, kluszon commented
@mcallegari All reported problems fixed. Please review it again.

2020-12-14 11:12 UTC, mcallegari approved these changes

2020-12-14 11:13 UTC, merged