Improve the tempo detection algorithm
mcallegari/qlcplus pull request #1306
Opened 2021-12-26 10:20 UTC by awwright

The Speed Dial widget features a "Tap" button that allows users to tap along with a beat, when choosing a duration.

Currently, this tap button only computes the time since the last tap. The computed value can be off by +-20ms. When tapping to music, this is enough to put the beat completely out-of-phase with the music in 10 seconds.

This patch records the most recent 20 taps, and computes the tempo that best passes through all of them. Within 10 taps it can compute a tempo that's correct +- 2ms. It's even robust against occasional missed taps.

The first tap uses the old (current) behavior, as does waiting more than 1.5 seconds in between a tap.

2021-12-26 17:49 UTC, mcallegari commented
Hi, before I review this, please indent your changes like the rest of the code. Thanks.

2021-12-26 22:10 UTC, awwright commented
@mcallegari Maybe you can help me out a bit, I'm not sure what you're referring to. The guidelines don't seem to be specific, but you seem to use 4-space indents, correct?

2021-12-27 01:00 UTC, awwright commented
I pushed an update that changed some of the variable names and whitespace around the `if` tokens, hopefully that helps.

Would you be interested in a PR that adds a linter for these things?

2021-12-29 16:25 UTC, mcallegari requested changes

2021-12-29 16:25 UTC, mcallegari commented on ui/src/speeddial.cpp
> +    while(m_tapHistory.count() > 16) m_tapHistory.removeFirst();
newline here please

2021-12-29 16:26 UTC, mcallegari commented
4-space tabs is correct.
No need for a linter right now.
Thanks

2021-12-31 08:11 UTC, mcallegari approved these changes

2021-12-31 08:35 UTC, merged

2021-12-31 08:54 UTC, mcallegari commented
Great, thanks :+1: