resources: add Eurolite LED PLL-480 CW/WW
mcallegari/qlcplus pull request #1496
Opened 2023-12-23 01:50 UTC by bdrung

Add Eurolite LED PLL-480 CW/WW [1]. The names and description were taken from 40001895-Manual-119588-1.000-de_en.pdf [2]. This fixture definition has some shortcomings:

1. There is no type for floodlights, so ColorChanger is used.
2. There are no separate presets for warm and cold white. So both warm and cold white have to use the same preset.
3. The bulb colour temperature field does not allow specifying the color range 3200K - 5600K. So the lower warm white colour is specified.

[1] https://www.steinigke.de/en/mpn40001895-eurolite-led-pll-480-cw-ww-panel.html
[2] https://www.steinigke.de/download/40001895-Manual-119588-1.000-eurolite-led-pll-480-cw-ww-panel-de_en.pdf

2023-12-23 09:16 UTC, mcallegari requested changes

2023-12-23 09:16 UTC, mcallegari commented on resources/fixtures/Eurolite/Eurolite-LED-PLL-480-CW-WW.qxf
> +  <Capability Min="0" Max="9">No function</Capability>
This should be "ShutterOpen" preset

2023-12-23 09:16 UTC, mcallegari commented on resources/fixtures/Eurolite/Eurolite-LED-PLL-480-CW-WW.qxf
> +  <Lens Name="Other" DegreesMin="0" DegreesMax="0"/>
Let's put a fixed 120 degrees min/max beam

2023-12-24 00:44 UTC, bdrung commented
Thanks. Addressed the comments. Where should I report those three points mentioned in commit message as feature request?

2023-12-24 07:28 UTC, mcallegari commented
You can report here:
https://www.qlcplus.org/forum/viewforum.php?f=18

2023-12-24 07:31 UTC, merged

2023-12-24 07:31 UTC, mcallegari commented
Thanks :+1: